### ISSUE TITLE
Monitor not changing state

### ISSUE THREAD

**Issue by Lucvdberg** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#12] opened 2017-11-02 14:25 UTC
Hi Zvi,
Here my question that I also posted in the community of squaredup.

Hi,

Has anyone experience with the SQL Query MP. I did some testing with a count query that returns values around 58 and set the monitor at ‘greater than 55’. I do the monitoring every 5 minutes and will give an alert by 2 samples. The monitor stays on the OK status. I need to do a recalculate to get this in error and after a refresh health it stays on OK.

Has anyone a solution for that?

Thanks,

Luc

**Comment by UretzkyZvi** [comment] 2017-11-02 22:45
I have done some changes.
Sorry but you would not to delete the current MPs in your SCOM environment and import new MPs
version 2.1.0.8 to keep it more easy to maintain I change library mp to version 2.1.0.8

[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

[QueryOleDbMonitorLibrary.mp](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)

I hope this will help.

If not, I will keep looking for the root cause of this problem

**Comment by snazy2000** [comment] 2017-11-03 12:18
Have just updated to 2.1.0.8, now trying to set this up again, performance is working as expected but as  Monitors / Alerts dont seem to be working :(

I have it set to check every 5 minutes and if greater than 0 then raise an alert (For 1 sample) but no alerts are generated

**Comment by UretzkyZvi** [comment] 2017-11-03 20:42
I fixed the issue with the monitor not change state

[QueryOleDbMonitorLibrary.mp](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)
[QueryOleDbMonitorTemplate.mpb](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

I will wait for your feedback before I will close the issue.
thanks

**Comment by snazy2000** [comment] 2017-11-06 11:47
Have installed the pack and now gone to edit and save and now get this :(

Note:  The following information was gathered when the operation was attempted.  The information may appear cryptic but provides context for the error.  The application will continue to run.

: Processing the template failed. See inner exception for details.
Verification failed with 1 errors:
-------------------------------------------------------
Error 1:
Found error in 2|UnknowMP|1.0.0.0|UnknowMP|| with message:
XSD verification failed for the management pack. [Line: 0, Position: 0]
System.Xml.Schema.XmlSchemaValidationException: The 'AlertParameter7' element is invalid - The value 'Provider=SQLOLEDB;Server=SERVER;Initial Catalog=DB;User Id=$RunAs[Name="OleDb.f32b5c9916d5482cbe098bc48fe21b48.SimpleAuthenticationAccount"]/UserName$;Password=$RunAs[Name="OleDb.f32b5c9916d5482cbe098bc48fe21b48.SimpleAuthenticationAccount"]/Password$' is invalid according to its datatype 'ManagementPackString' - The actual length is greater than the MaxLength value. ---> System.Xml.Schema.XmlSchemaException: The actual length is greater than the MaxLength value.
   --- End of inner exception stack trace ---
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
   at System.Xml.Schema.XmlSchemaValidator.CheckElementValue(String stringValue)
   at System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(String stringValue, XmlSchemaSimpleType& memberType)
   at System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(XmlSchemaInfo schemaInfo, Object typedValue)
   at System.Xml.XsdValidatingReader.ProcessEndElementEvent()
   at System.Xml.XsdValidatingReader.Read()
   at Microsoft.EnterpriseManagement.Configuration.XSDVerification.ValidateManagementPack(TextReader mpcontents, ManagementPack mp, Boolean throwError)
-------------------------------------------------------
XSD verification failed for the management pack. [Line: 0, Position: 0]
: Verification failed with 1 errors:
-------------------------------------------------------
Error 1:
Found error in 2|UnknowMP|1.0.0.0|UnknowMP|| with message:
XSD verification failed for the management pack. [Line: 0, Position: 0]
System.Xml.Schema.XmlSchemaValidationException: The 'AlertParameter7' element is invalid - The value 'Provider=SQLOLEDB;Server=SERVER;Initial Catalog=DB;User Id=$RunAs[Name="OleDb.f32b5c9916d5482cbe098bc48fe21b48.SimpleAuthenticationAccount"]/UserName$;Password=$RunAs[Name="OleDb.f32b5c9916d5482cbe098bc48fe21b48.SimpleAuthenticationAccount"]/Password$' is invalid according to its datatype 'ManagementPackString' - The actual length is greater than the MaxLength value. ---> System.Xml.Schema.XmlSchemaException: The actual length is greater than the MaxLength value.
   --- End of inner exception stack trace ---
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
   at System.Xml.Schema.XmlSchemaValidator.CheckElementValue(String stringValue)
   at System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(String stringValue, XmlSchemaSimpleType& memberType)
   at System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(XmlSchemaInfo schemaInfo, Object typedValue)
   at System.Xml.XsdValidatingReader.ProcessEndElementEvent()
   at System.Xml.XsdValidatingReader.Read()
   at Microsoft.EnterpriseManagement.Configuration.XSDVerification.ValidateManagementPack(TextReader mpcontents, ManagementPack mp, Boolean throwError)
-------------------------------------------------------


: XSD verification failed for the management pack. [Line: 0, Position: 0]

**Comment by UretzkyZvi** [comment] 2017-11-06 13:54
I did not know but it turns out that the AlertParameter value has a max size of 256 characters.
which means I will have to remove the connection string and query string from an alert description.

Thanks

**Comment by UretzkyZvi** [comment] 2017-11-06 14:51
DONE! current alert example
![image](https://user-images.githubusercontent.com/6106808/32446526-d8cbd52c-c311-11e7-8861-4c3cd330c6b0.png)

[QueryOleDbMonitorLibrary](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorLibrary.mp)

[QueryOleDbMonitorTemplate](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/raw/master/ManagementPacks/QueryOleDbMonitorTemplate.mpb)

**Comment by snazy2000** [comment] 2017-11-06 17:58
Seems to be working as expected now ! :)

**Comment by UretzkyZvi** [comment] 2017-11-06 18:30
Great !!

**Closed** 2017-11-06 18:53 UTC
